ajk/diagonal shift multisubgrid
amanzi/amanzi pull request #526
Opened 2021-03-02 01:13 UTC by ajkhattak

1. Previously diagonal shift, to avoid nonsingular Jacobian, was applied globally to the matrix. In this PR, we apply a small shift (1.e-6) to non-zero diagonal term and a relatively bigger shift (which is need in highly nonlinear surface-standalone flows and specified by the user). This approach works very well for our Arctic multiscale model.
2. PK_DomainFucntionSubridReturn is extended to **multi-subgrid** stream-hyporheic transport models.

2021-03-03 18:45 UTC, ajkhattak commented on src/data_structures/MatrixFE.cc
> +  for (int i=0; i!=diag.MyLength(); ++i) {
I see...  I can try your suggestion DiagonalShiftAdaptive(shift, value) too.

2021-03-03 20:17 UTC, lipnikov approved these changes

2021-03-05 03:33 UTC, ecoon requested changes
See comments -- big one is the switch to use the DomainSet rather than hard-code iterating over all cells.

2021-03-05 03:33 UTC, ecoon commented on src/data_structures/MatrixFE.cc
> +  for (int i=0; i!=diag.MyLength(); ++i) {
I'm a little concerned that this results in step discontinuities -- small changes in diag[I] result in shift_major - shift_minor changes in the shift.

Would something like:

```
DiagonalShiftFloor(double floor) {
  diag[I] = max(diag[I], floor);
}
```
do what you're looking for?  This seems safer to me.

2021-03-05 03:33 UTC, ecoon commented on src/pks/PK_DomainFunctionSubgridReturn.hh
> +      domain << field_out_prefix_ << ":" << gid << "-";
Don't compose these manually please -- use the functions in Keys `Keys::getDomainInSet(field_out_prefix_,gid)`

But this class should get the DomainSet object from State, and iterate over that rather than hard-coding the name anyway.  What happens when you want two sub grid models on a secondary river, and one sub grid model on a primary stream?  Or only use subgrid models on a single reach?  You should be able to define DomainSets on arbitrary subsets of the mesh, not just "all cells" like is hardcoded here.  So rather than looping over cells, the pattern should be:

1. get the DomainSet name from the parameter list
2. At some point, get the DomainSet from State
3. loop over domains in the set:

```
for (const auto& domain : domain_set) {
  int gid = Keys::getDomainSetIndex<int>(domain);
  int c = map.LID(gid);
  // do stuff
}

2021-03-05 03:33 UTC, ecoon commented on src/state/State.cc
> +    domain_sets_(other.domain_sets_),
Thanks for fixing this!

2021-03-05 03:33 UTC, ecoon commented on src/pks/PK_DomainFunctionSubgridReturn.hh
> +  if (blist.isParameter("subgrid field prefix"))
This parameter should be called "subgrid domain name" or "subgrid domain set".  The user would provide either "subgrid:*" or "subgrid".

2021-03-05 23:03 UTC, lipnikov commented on src/pks/PK_DomainFunctionSubgridReturn.hh
> +	// find the subgrid gid to be integrated
Missing indentation?

2021-03-06 02:17 UTC, ajkhattak commented on src/data_structures/MatrixFE.cc
> +  for (int i=0; i!=diag.MyLength(); ++i) {
I think what I am trying to do is to cover a relatively wider range of flow gradients. A fixed smaller shift (e.g., 1E-5) works when the flow gradient between the two neighboring cells is more or less on the same order of magnitude as the shift. As the flow gradient gets bigger this fixed smaller shift does not work, especially in the case when one cell is totally dry and other is wetter, and then a major shift is needed. Looking at the logic in DiagonalShiftAdaptive, the major shift is only applied to a totally dry cell which helped based on my experience. To be more specific, the shift_minor_=1E-3 and shift_major = 10 worked well for my 100-year Arctic projections. Sorry, what is "double floor" here? I have to try it in a 100-year run before I say if it will work or not.

2021-03-09 18:38 UTC, ajkhattak commented on src/pks/PK_DomainFunctionSubgridReturn.hh
> +      domain << field_out_prefix_ << ":" << gid << "-";
This is done. Please have a look.

2021-03-11 14:32 UTC, ecoon approved these changes
Let's talk about the diagonal shift quickly, but otherwise this looks much better.

2021-03-11 14:32 UTC, ecoon commented on src/pks/PK_DomainFunctionSubgridReturn.hh
> +	value_[*c] = val;
Good, this looks much cleaner to me.

2021-03-11 19:18 UTC, ajkhattak commented on src/data_structures/MatrixFE.cc
> +  for (int i=0; i!=diag.MyLength(); ++i) {
Done!

2021-03-11 20:27 UTC, merged