Naren/sw
amanzi/amanzi pull request #682
Opened 2022-08-15 02:52 UTC by nvohra0016

Flow over dry beds. Scheme as in [Beljadid et al' 16].

2022-08-15 23:46 UTC, lipnikov commented on src/pks/shallow_water/NumericalFlux_Rusanov.cc
> +  Smax = 1.e0 * std::max(SL, SR);
Multiplication by 1.

2022-08-15 23:51 UTC, lipnikov commented on src/pks/shallow_water/ShallowWater_PK.cc
> +  Teuchos::RCP<Teuchos::ParameterList> pk_list =
I think we decided to allow 100 characters in one line. Please change this in the script and rerun it.

2022-08-16 00:10 UTC, lipnikov requested changes
I suggest first to reformat for 100-character lines as in master::src/.clang-format

2022-08-16 23:12 UTC, lipnikov commented on src/pks/shallow_water/ShallowWater_PK.cc
> +    cell_area_max_ = std::max(cell_area_max_, mesh_->cell_volume(c) * mesh_->cell_volume(c));
Do a * a outside the loop. Also, rename cell_area_max to cell_area2_max_ to code readibility.

2022-08-16 23:26 UTC, lipnikov commented on src/pks/shallow_water/ShallowWater_PK.cc
> +  for (int c = 0; c < ncells_wghost; ++c) {
h_old has no ghost values. Even if you require them, you need to distribute them.

2022-08-16 23:37 UTC, lipnikov commented on src/pks/shallow_water/ShallowWater_PK.cc
> +  for (int c = 0; c < ncells_wghost; ++c) {
Similar to above, h_temp has no ghost values.

2022-08-16 23:43 UTC, lipnikov commented on src/pks/shallow_water/ShallowWater_PK.cc
> +  auto& ht_c = *S_->GetW<CompositeVector>(total_depth_key_, passwd_).ViewComponent("cell", true);
Can you use total_depth_key_ here?  It is called inside a time integrator with a vector not necessary from the State.

2022-08-16 23:46 UTC, lipnikov requested changes
My understanding that requested work could be essential. Please reply before I continue.

2022-08-16 23:55 UTC, lipnikov commented on src/pks/shallow_water/test/shallow_water_dry_bed.cc
> +    *S->Get<CompositeVector>("surface-bathymetry").ViewComponent("cell");
Looks like this file was not reformatted for 100-char lines

2022-08-17 00:04 UTC, lipnikov commented on src/pks/shallow_water/ShallowWater_PK.cc
> +  if ((ht_c[0][c] > Bmax) && (ht_c[0][c] - B_c[0][c] > 1.e-15)) {
This is dangerous. If h and B about 100 m, the difference has only 14 valid digits. Should we use a relative tolerance here? Also, it would be better to place it at the top of routine. Another good place to various tolerances is ShallowWaterDefs.hh as we do in other PKs.

2022-08-17 00:05 UTC, lipnikov commented on src/pks/shallow_water/ShallowWater_PK.cc
> +  // characterize cell based on [Beljadid et al.' 16]
Add journal also.

2022-08-17 02:07 UTC, nvohra0016 commented on src/pks/shallow_water/ShallowWater_PK.cc
> +  auto& ht_c = *S_->GetW<CompositeVector>(total_depth_key_, passwd_).ViewComponent("cell", true);
So would it be better to pass ht_c as an argument in the function?

2022-08-17 03:04 UTC, lipnikov commented on src/pks/shallow_water/ShallowWater_PK.cc
> +  auto& ht_c = *S_->GetW<CompositeVector>(total_depth_key_, passwd_).ViewComponent("cell", true);
Eventually, this may be required. But I'm more concern of the logic, say, in context of RK2.

2022-08-17 03:13 UTC, nvohra0016 commented on src/pks/shallow_water/ShallowWater_PK.cc
> +  auto& ht_c = *S_->GetW<CompositeVector>(total_depth_key_, passwd_).ViewComponent("cell", true);
Hmm, I see, but we recompute the total depth ht_c in the time integrator (ShallowWater_TI.cc), so it should be fine? 
[
](https://github.com/amanzi/amanzi/blob/ed9f9057854faa9c84bcd91b46d12fab7a0f5829/src/pks/shallow_water/ShallowWater_TI.cc#L55)

That means that the intermediate values of ht_c are used, say, in RK2 for the total depth reconstruction?

2022-08-17 15:42 UTC, nvohra0016 commented on src/pks/shallow_water/ShallowWater_PK.cc
> +  auto& ht_c = *S_->GetW<CompositeVector>(total_depth_key_, passwd_).ViewComponent("cell", true);
I have made some changes in the implementation. Now only the nodal bathymetry is passed as an argument and the rest of the values (like total depth) are passed as scalars.

2022-08-17 16:30 UTC, lipnikov commented on src/pks/shallow_water/ShallowWater_PK.cc
> +  auto& ht_c = *S_->GetW<CompositeVector>(total_depth_key_, passwd_).ViewComponent("cell", true);
Okay.

2022-08-17 16:31 UTC, lipnikov commented on src/pks/shallow_water/ShallowWater_PK.hh
> +  std::vector<double> NumericalSource(int c, double htc, double Bc, const Epetra_MultiVector B_n);
You need to pass by reference.

2022-08-17 16:43 UTC, lipnikov commented on src/pks/shallow_water/ShallowWater_PK.cc
> +  	Bmax = std::max(B_n[0][cnodes[i]], Bmax);
From one angle it makes sense to precompute and cache this field since bathymetry is static. However, it may vary in the future due deposition, so probably we should not do it. Just a comment to think a lit, no action is needed.

2022-08-17 16:45 UTC, lipnikov commented on src/pks/shallow_water/ShallowWater_PK.cc
> +  if (cell_is_fully_flooded == true) {
We use if (a) {} in amanzi, if a is boolean.

2022-08-17 16:48 UTC, lipnikov commented on src/pks/shallow_water/ShallowWater_PK.cc
> +      Amanzi::AmanziGeometry::Point area_cross_product = (0.5) * tria_edge0 ^ tria_edge1;
= 0.5 * ((xc - x0) ^ (xc - x1))  would be shorter

2022-08-17 16:51 UTC, lipnikov commented on src/pks/shallow_water/ShallowWater_PK.cc
> +      double area = norm(area_cross_product);
I think this is even better  area = norm((xc - x0) ^ (xc - x1)) / 2;

2022-08-17 16:52 UTC, lipnikov commented on src/pks/shallow_water/ShallowWater_PK.cc
> +      mesh_->node_get_coordinates(face_nodes[0], &x0);
Suggest to define n0 = face_nodes[0] and use it later, for code readability.

2022-08-17 16:55 UTC, lipnikov commented on src/pks/shallow_water/ShallowWater_PK.cc
> +      double ht_rec_x0 = htc;
What is the reason for renaming htc?  Compiler will optimize it out... still?

2022-08-17 16:58 UTC, lipnikov commented on src/pks/shallow_water/ShallowWater_PK.cc
> +  for (int c = 0; c < ncells_wghost; c++) {
Why do u need ghosts here?

2022-08-17 16:59 UTC, lipnikov commented on src/pks/shallow_water/ShallowWater_PK.cc
> +  if (iters_ < max_iters_) {
Are brackets {} due to re-formatting?

2022-08-17 18:15 UTC, lipnikov commented on src/pks/shallow_water/test/shallow_water_1D_dry_bed.cc
> +      double area = norm(area_cross_product);
I suggest area = norm ((xc - x0)^(xc - x1)) / 2;

2022-08-17 18:19 UTC, lipnikov commented on src/pks/shallow_water/test/shallow_water_1D_dry_bed.cc
> +      io.WriteVector(*hh(0), "depth", AmanziMesh::CELL);
Eventually, we may create help I/O functions and use them in all tests, probably after a merge.

2022-08-17 18:25 UTC, lipnikov commented on src/pks/shallow_water/test/shallow_water_lake_at_rest.cc
> +
If this file was not modified due to new capabilties, let us remove all re-formatting by checking out the original version. Reason is that future potential debugging will be easier with smaller number of changes.

2022-08-17 18:26 UTC, lipnikov approved these changes
Approval is contingent to resolving my comments.

2022-08-17 18:59 UTC, nvohra0016 commented on src/pks/shallow_water/ShallowWater_PK.cc
> +  if ((ht_c[0][c] > Bmax) && (ht_c[0][c] - B_c[0][c] > 1.e-15)) {
Fixed. Only needed positivity of (ht_c - B_c). Had 1.e-15 for debugging purposes earlier.

2022-08-17 19:02 UTC, nvohra0016 commented on src/pks/shallow_water/ShallowWater_PK.cc
> +      double ht_rec_x0 = htc;
Fixed. Was using that for debugging purposes earlier.

2022-08-17 19:02 UTC, nvohra0016 commented on src/pks/shallow_water/ShallowWater_PK.cc
> +  	Bmax = std::max(B_n[0][cnodes[i]], Bmax);
I see what you mean.

2022-08-17 20:01 UTC, nvohra0016 commented on src/pks/shallow_water/test/shallow_water_lake_at_rest.cc
> +
Okay

2022-08-17 21:15 UTC, nvohra0016 commented on src/pks/shallow_water/ShallowWater_PK.cc
> +  if (iters_ < max_iters_) {
I am unsure. They may have moved due to re-formatting.

2022-08-17 21:54 UTC, merged