Add Pipe Flow PK
amanzi/amanzi pull request #824
Opened 2024-04-03 13:59 UTC by gcapodag

This PR adds a pipe flow PK, which solves the 1D Saint Venant equations (in a 2D domain). The pipe flow can be coupled during the time integration step with a junction model that solves the 2D SW equations, with an additional friction term compared to the current SW PK. Pipe flow + junctions form the pipe network, which can be coupled with an overland flow model, where water can move from the surface down into the network and back up, in case overflow occurs. The pipe network model has been tested and is mass conserving, and preserves steady state initial conditions, similarly to the SW model. Tests currently exist to provide continuous integration and will soon be included in an ats-regression-tests suite PR.
The pipe flow model in standalone mode has been tested against experimental data with the hydraulic routing test from [Liu and Chen](https://ascelibrary.org/doi/full/10.1061/(ASCE)HY.1943-7900.0002011), see pictures below, showing results that are consistent with those in the aforementioned paper. Please also see the companion PR in ATS for the pipe drain evaluator regulating the water exchange between pipe network and overland flow: https://github.com/amanzi/ats/pull/253
<img width="500" alt="hyd1" src="https://github.com/amanzi/amanzi/assets/10819458/6ef524a6-e98b-460f-b13a-a64f6bdd778f">
<img width="500" alt="hyd2" src="https://github.com/amanzi/amanzi/assets/10819458/4029aa0b-1a3a-44e8-9297-da486bacc375">

2024-04-03 14:01 UTC, gcapodag commented
@lipnikov thanks for the suggestion and for looking at the PR. It was easier to close the other PR and re-open it like this, so the commits are squashed and the branch is rebased to the latest commit on master, as you suggested. I also reformatted the code with the clang-format in tools/formatting. Thanks.

2024-04-03 16:53 UTC, lipnikov commented on src/pks/shallow_water/DischargeEvaluator.cc
> +  if (domain == "surface" || domain == "street") {
Optional comment: if this is a generic evaluator, we may consider in the future passing the primary variable name via plist's parameter "primary variable key".

2024-04-03 16:56 UTC, lipnikov commented on src/pks/shallow_water/NumericalFlux_CentralUpwind.cc
> +    U_star[i] = (apx * UR[i] - amx * UL[i] - (FR[i] - FL[i])) / (apx - amx + eps1);
U_star is computed twice.

2024-04-03 17:00 UTC, lipnikov commented on src/pks/shallow_water/PipeFlow_PK.cc
> +      abort();
Use Exceptions::amanzi_throw(msg) instead

2024-04-03 17:54 UTC, lipnikov requested changes
I see pictures in the PR description but there are no tests. Typically, we require tests to
support new capability via CI. Can you share files used to create pictures? Can we converter these files to tests in a subsequent PR?

2024-04-03 17:54 UTC, lipnikov commented on src/pks/shallow_water/PipeFlow_PK.cc
> +      abort();
Use amanzi_throw(msg)

2024-04-03 17:54 UTC, lipnikov commented on src/pks/shallow_water/PipeFlow_PK.cc
> +    1.e-10) { //we have to raise this to the power of 7/3 below so the tolerance needs to be stricter
Move the comment above if() so the formatter will not break if () into multiple lines.

2024-04-03 17:54 UTC, lipnikov commented on src/pks/shallow_water/PipeFlow_PK.cc
> +  double PipeCrossSection = Pi * 0.25 * PipeD * PipeD;
Use M_PI constant from math.h instead of internal Pi.

2024-04-03 17:54 UTC, lipnikov commented on src/pks/shallow_water/PipeFlow_PK_reg.hh
> +RegisteredPKFactory<PipeFlow_PK> PipeFlow_PK::reg_("pipe flow");
We have pls_shallow_water_reg.hh. Typically we use one registration file per PK, e.g. see Flow PK. If you think that a separate header is needed, please rename it to pks_pipe_flow_reg.hh for consistency

2024-04-03 17:54 UTC, lipnikov commented on src/pks/shallow_water/PressureHeadEvaluator.cc
> +    double pipeCrossSection = Pi * 0.25 * PipeD_c[0][c] * PipeD_c[0][c];
Use M_PI from math.h

2024-04-03 17:54 UTC, lipnikov commented on src/pks/shallow_water/ShallowWater_PK.hh
> +  void PushBackBC(Teuchos::RCP<ShallowWaterBoundaryFunction> bc) { bcs_.push_back(bc); };
I do not think that this function helps code readability. What is the reason for this renaming?

2024-04-03 17:54 UTC, lipnikov commented on src/pks/shallow_water/ShallowWater_PK.hh
> +  double Pi = 3.14159265359;
Remove Pi, use M_PI instead. This implies that TwoPi should be removed too in favor of 2 * M_PI

2024-04-03 17:54 UTC, lipnikov commented on src/pks/shallow_water/test/shallow_water_lake_at_rest_case2.xml
> +            <Parameter name="regions" type="Array(string)" value="{}"/>
Strange. If there are no BC, remove the whole sublist for it.

2024-04-03 17:54 UTC, lipnikov commented on src/pks/shallow_water/test/shallow_water_lake_at_rest_case2.xml
> +            <Parameter name="regions" type="Array(string)" value="{}"/>
Same as above

2024-04-03 17:54 UTC, lipnikov commented on src/pks/shallow_water/test/shallow_water_lake_at_rest_case1.xml
> +            <Parameter name="regions" type="Array(string)" value="{}"/>
Same as above. No region -> remove the whole sublist

2024-04-03 17:54 UTC, lipnikov commented on src/pks/shallow_water/test/shallow_water_lake_at_rest_case1.xml
> +            <Parameter name="regions" type="Array(string)" value="{}"/>
Same as above

2024-04-03 17:54 UTC, lipnikov commented on src/pks/shallow_water/pks_shallow_water_registration.hh
> +} // namespace ShallowWater
No reason to repeat namespaces Amanzi and ShallowWater twice

2024-04-03 17:54 UTC, lipnikov commented on src/pks/shallow_water/WaterDepthEvaluator.hh
> +  double TwoPi = 6.28318530718;
Remove. For consistence better to use 2 * M_PI everywhere... would be easier to debug in the future.

2024-04-03 17:54 UTC, lipnikov commented on src/pks/shallow_water/PressureHeadEvaluator.hh
> +  double Pi = 3.14159265359;
Use M_PI and 2 * M_PI for consistency.

2024-04-03 18:29 UTC, gcapodag commented
Thanks a lot @lipnikov , I'll start addressing your comments right away

2024-04-03 18:40 UTC, gcapodag commented on src/pks/shallow_water/DischargeEvaluator.cc
> +  if (domain == "surface" || domain == "street") {
Yes, that is a good idea. If you don't mind let's keep it as a future improvement.

2024-04-03 19:05 UTC, gcapodag commented on src/pks/shallow_water/ShallowWater_PK.hh
> +  void PushBackBC(Teuchos::RCP<ShallowWaterBoundaryFunction> bc) { bcs_.push_back(bc); };
It may be the residual of previous code development, you are right now it does not make sense to have it anymore. I removed it.

2024-04-03 19:05 UTC, gcapodag commented on src/pks/shallow_water/test/shallow_water_lake_at_rest_case2.xml
> +            <Parameter name="regions" type="Array(string)" value="{}"/>
I think @nvohra0016 did this so I am going to leave that to him.

2024-04-03 19:05 UTC, gcapodag commented on src/pks/shallow_water/test/shallow_water_lake_at_rest_case2.xml
> +            <Parameter name="regions" type="Array(string)" value="{}"/>
I think @nvohra0016 did this so I am going to leave that to him.

2024-04-03 19:05 UTC, gcapodag commented on src/pks/shallow_water/test/shallow_water_lake_at_rest_case1.xml
> +            <Parameter name="regions" type="Array(string)" value="{}"/>
I think @nvohra0016 did this so I am going to leave that to him.

2024-04-03 19:06 UTC, gcapodag commented on src/pks/shallow_water/test/shallow_water_lake_at_rest_case1.xml
> +            <Parameter name="regions" type="Array(string)" value="{}"/>
I think @nvohra0016 did this so I am going to leave that to him.

2024-04-03 19:08 UTC, gcapodag commented on src/pks/shallow_water/PipeFlow_PK.cc
> +      if (normal[0] > 1.e-08) { //this identifies the j+1/2 face
Thanks for the comment. What do you think is the best way to proceed?

2024-04-03 19:21 UTC, gcapodag commented
@lipnikov yes, in the future appropriate automated tests will be included in a separate PR. At the moment, all tests are in the branch `giacomo/urban_storm_drains` of `ats-regression-tests`, and can be found [here](https://github.com/amanzi/ats-regression-tests/tree/giacomo/urban_storm_drains/12_shallow_water). For instance, the plot shown above (only the numerical curve, not the experimental data) is obtained running `pipe_flow_hydraulic_routing.xml` and then doing a plot over time in Paraview at x=8.89 or x=77.47. There are also several `lake_at_rest` tests that can be run to verify the preservation of the steady state initial condition. For mass conservation, one can run `excalibur_mesh_water_balance.xml`, `coupled_surface_pipe_model_water_balance.xml` or `coupled_surface_pipe_model_water_balance_junction.xml`. All there of these output an observation file, that can be used as input for Python scripts that sit in [this repo](https://github.com/gcapodag/amanzi_water_balance)  that verify that mass is conserved up to machine precision. The observation files have to be renamed and also deprived of the initial headers and quotes before they can be read in by the Python scripts. At some point all this will be automated and included in an appropriate PR, as I mentioned. One important note is that when I try to run these tests with the `ats` executable that uses the PR code, I get an HDF5 error that prevents me from running. If I use the "old version code" from `giacomo/urban_storm_drains` that is not up to date with master, then the error does not show and everything runs. @nvohra0016 has seen the same problem. The "old version code" uses the 0.98.6 version of the TPLs.

2024-04-03 20:34 UTC, lipnikov commented on src/pks/shallow_water/PipeFlow_PK.cc
> +      if (normal[0] > 1.e-08) { //this identifies the j+1/2 face
I would consider normal[0] > tol * area,  where area is the face area, unless normal was already rescaled inside ProjectNormalOntoMeshDirection()

2024-04-03 20:41 UTC, lipnikov commented
"The pipe flow model in standalone mode has been tested against experimental data with the hydraulic routing test from [Liu and Chen]" This could be converted to an Amanzi test if it runs fast enough. Amanzi does not test ATS regressions on a regular basis so it is important to have one-two Amanzi tests to prevent breaking ATS. I presume that experimental data are available from this paper.

2024-04-03 21:37 UTC, lipnikov commented
I think you need only 1 registration file pks_shallow_water_reg.hh

2024-04-03 21:49 UTC, jd-moulton commented
I think this is progressing really well. Thanks @gcapodag for updating this code to be consistent with updates to the mesh infrastructure and state on the master branch.  Also, thanks @lipnikov  for already reviewing the PK and coupling code.  

As noted earlier, the final approval will depend on having at least a couple of tests (since there's arguably at least two key models under the pipe flow PK - the pipe flow itself, and the junctions) included in Amanzi's testing framework.   I don't think it will take @nvohra0016 long to migrate those from the ats-regression-tests repository to the PK here to run under a separate test binary or amanzi, although he has other deadlines this week.   The coupled tests can then be developed under ATS regression testing, but I don't think they need to be completed before we accept this PR. 

Also, we would typically want a demonstration of the new PKs in the Amanzi User Guide.  This is an interesting case because the new PKs are mostly used under ATS, so a bit of an open question as to where to put all the documentation and how much to worry about duplication.  

The underlying issue with hdf5 needs be resolved as well it makes sense to merge this PR.  I don't think this will take all that long, but we have other deadlines this week.

2024-04-04 19:54 UTC, gcapodag commented on src/pks/shallow_water/PipeFlow_PK.cc
> +      if (normal[0] > 1.e-08) { //this identifies the j+1/2 face
I see that in the TI function, the normal is scaled by the face area but in the bed slope source code (the one you mentioned here) it is not (and it is not scaled in ProjectNormalOntoMeshDirection()), so I would go with your suggestion of having tol * area.

2024-04-05 23:54 UTC, gcapodag commented
Hi all, I made the necessary changes to have all Amanzi CI tests passing. Interestingly, the `shallow_water_Thacker` was failing because I had not switched  to the new mesh framework a call to setup the ponded depth BC, though it would still compile with no errors. I also integrated @nvohra0016 's changes from last November to one of the mpc tests that was failing. Thanks again @lipnikov  for being so quick and helpful!

2024-10-06 20:36 UTC, merged

2024-10-06 21:15 UTC, gcapodag commented
Thank you so much @nvohra0016 , great work!